/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddShift: typeof import('./src/components/AddShift.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    LoginRegister: typeof import('./src/components/LoginRegister.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
